name: Close Stale Issues

on:
  schedule:
    - cron: "0 0 */7 * *" # æ¯15å¤©åˆå¤œè¿è¡Œä¸€æ¬¡
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9 # ä½¿ç”¨å®˜æ–¹çš„ stale action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "ğŸ•’ Discussion Activity Reminder ğŸ•’\n\nThis Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:\n\n1ï¸âƒ£ Close as Out of Date: If the topic is no longer relevant, close the Discussion as out of date at the bottom of the page.\n\n2ï¸âƒ£ Provide More Information: Share additional details or context â€” or let the community know if you've found a solution on your own.\n\n3ï¸âƒ£ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.\n\nNote: This dormant notification will only apply to Discussions with the Question label. To learn more, see our recent announcement.\n\nThank you for helping bring this Discussion to a resolution! ğŸ’¬"
          stale-pr-message: "This pull request or issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          days-before-stale: 60 # 30å¤©æ²¡æœ‰æ´»åŠ¨çš„ issue ä¼šè¢«æ ‡è®°ä¸ºé™ˆæ—§
          days-before-close: 7 # è¢«æ ‡è®°ä¸ºé™ˆæ—§åå†ç»è¿‡7å¤©æ²¡æœ‰æ´»åŠ¨çš„ issue ä¼šè¢«è‡ªåŠ¨å…³é—­
          stale-issue-label: "action-stale" # æ ‡è®°é™ˆæ—§ issue çš„æ ‡ç­¾
          close-issue-label: "not-completed"
          exempt-issue-labels: "keep-open" # å¸¦æœ‰è¿™ä¸ªæ ‡ç­¾çš„ issue ä¸ä¼šè¢«æ ‡è®°ä¸ºé™ˆæ—§
