name: Lint pushes/PRs

on: [push, pull_request]

jobs:
  js-json-md-yaml-lint:
    name: JavaScript + JSON + Markdown + YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci # instead of install to ensure consistency and determinism in CI/CD workflow

      - name: Run ESLint
        run: npm run lint
