name: translate-repo-md

on:
  workflow_run:
    workflows: ["update-docs-readme-list"] # æ›´æ–°äº†ä»“åº“è‡ªè¿°æ–‡ä»¶,è§¦å‘ç¿»è¯‘
    types:
      - completed
  workflow_dispatch:

jobs:
  translate-readme:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: è¯»å–å¹¶ç¿»è¯‘ README
        run: |
          python utils/translate_force_chinese_to_lang.py

      - name: æäº¤å’Œæ¨é€æ›´æ”¹
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global user.name 'qinwuyuan-sync-bot'
          git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
          git pull
          git add .
          git commit -n -S -m "docs(ci): ğŸ“ è°·æ­Œç¿»è¯‘[\`README.md\`]â†’[\`{vi,ko,en,jp,zh-TW}/README.md\`]" || echo "æ²¡æœ‰éœ€è¦æäº¤çš„æ›´æ”¹"
          git push
