name: update-docs-readme-list

on:
  workflow_run:
    workflows:
      - "update-scripts-version" #è§¦å‘äº†è‡ªåŠ¨æ›´æ–°.
      - "merge-change-history" #è§¦å‘äº†åˆå¹¶å†å²è®°å½•,å¯èƒ½jsonæ–‡ä»¶è¢«æ”¹å˜,
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: update-qinwuyuan-UserScripts-2
  cancel-in-progress: false

jobs:
  update-script-list:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install requests

      - name: æ‰§è¡ŒREADME.mdæ›´æ–°.åˆ·æ–°greasyforkæ•°æ®
        run: |
          python utils/update_scripts_list.py

      - name: æäº¤å’Œæ¨é€æ›´æ”¹
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global user.name 'ChinaGodBot'
          git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
          git pull
          git add .
          git commit -n -S -m "docs(ci): ğŸ“ æ›´æ–°è„šæœ¬è¡¨æ ¼[\`ScriptsPath.json\`]â†’[\`README.md\`]" || echo "æ²¡æœ‰éœ€è¦æäº¤çš„æ›´æ”¹"
          git push || git pull --rebase && git push
