name: update-docs-readme-list

on:
  #workflow_run:
  #  workflows:
  #    - "merge-change-history" # æ“ä½œæ‰€æœ‰raedme.mdååˆ·æ–°[docs/README.md]ä¸­çš„åˆ—è¡¨
  #  types:
  #    - completed
  workflow_dispatch:

jobs:
  update-script-list:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.QWY_SYNC_BOT_TOKEN }}

      - name: Install dependencies
        run: |
          pip install requests

      - name: æ‰§è¡ŒREADME.mdæ›´æ–°.åˆ·æ–°greasyforkæ•°æ®
        run: |
          python utils/update_scripts_list.py
      - name: è®¾ç½®æœºå™¨äººæäº¤
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name 'ChinaGodBot'
          git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
      - name: æäº¤å’Œæ¨é€æ›´æ”¹
        run: |
          git pull
          git add .
          git commit -n -m "docs(ci): ğŸ“ æ›´æ–°è„šæœ¬è¡¨æ ¼[\`ScriptsPath.json\`]â†’[\`README.md\`]" || true
          git push
          if [ $? -ne 0 ]; then
            git pull --rebase
            git push
          fi
