name: update-docs-readme-list

on:
    workflow_run:
        workflows:
            - "update-scripts-version" #触发了自动更新.
            - "merge-change-history" #触发了合并历史记录,可能json文件被改变,
        types:
            - completed
    workflow_dispatch:

concurrency:
    group: update-qinwuyuan-UserScripts-2
    cancel-in-progress: false

jobs:
    update-script-list:
        runs-on: ubuntu-latest
        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  pip install requests

            - name: 执行README.md更新.刷新greasyfork数据
              run: |
                  python pythonscr/update-script-list/upadate-greasyfork.py
                  python pythonscr/update-script-list/update-script-list.py

            - name: 提交和推送更改
              run: |
                  gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
                  git config --global user.name 'qinwuyuan-sync-bot'
                  git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
                  git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
                  git pull
                  git add .
                  git commit -S -m '更新readme脚本列表[docs/ScriptsPath.json→/docs/README.md]' || echo "没有需要提交的更改"
                  git push
